### PR TITLE
[IMP] stock_full_location_reservation: Be able to merge the new movement for the whole quantity

### PR DESCRIPTION
**Pull request by rousseldenis**
@jbaudoux

### CODE REVIEW

**Comment by jbaudoux** [comment]
Note @mt-software-de : This is because stock_storage_type chaotic put-away computes different destination location for each move of the transfer

**Comment by mt-software-de** [comment]
@rousseldenis could you also Backport this to Version 14.0?

**Comment by rousseldenis** [comment]
@mt-software-de Wait before merging. Some flows don't work

**Comment by rousseldenis** [comment]
@mt-software-de This one is ready

**Comment by rousseldenis** [comment]
@mt-software-de @jbaudoux Do you plan to integrate this ?

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
> @rousseldenis could you also Backport this to Version 14.0?

@mt-software-de ATM, we don't need this in v14 as we don't compute any putaway

**Pull request merged**
